#!/usr/bin/env python3
"""agentic_probe.py — probe the OBSERVED agentic surface of the registry's top repos.

For every 🥇 (rank 1) repo in knowledge/graph.json with a GitHub link, list its root
tree via the GitHub API and record which agent-facing artifacts it actually ships —
AGENTS.md, CLAUDE.md, llms.txt, SKILL.md, .mcp.json, .claude/{skills,hooks,commands},
.claude-plugin / .codex-plugin / .cursor-plugin, a skills/ dir + skills-manifest.json.

Honesty rules (BRACE discipline): evidence is a 200 from the repo itself — never a blog
or a hunch. A repo that fails to probe is "not measured" and is OMITTED from the overlay
(never recorded as "no tooling"); any probe error exits non-zero so CI can't fake green.

Usage:
  agentic_probe.py [--graph knowledge/graph.json] [--out knowledge/agentic.json] [--rank 1]
Auth: set GITHUB_TOKEN to lift the anonymous API rate limit (60/hr). Stdlib only.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request

# root entry name → surface token (what an agent can key off)
_ROOT_SURFACES = {
    "AGENTS.md": "agents-md",
    "CLAUDE.md": "claude-md",
    "llms.txt": "llms-txt",
    "SKILL.md": "skill-md",
    ".mcp.json": "mcp-config",
    ".claude-plugin": "claude-plugin",
    ".codex-plugin": "codex-plugin",
    ".cursor-plugin": "cursor-plugin",
    ".cursorrules": "cursor-rules",
    ".agents": "agents-dir",
    "skills": "skills-dir",
    "skills-manifest.json": "skills-manifest",
}
# entries inside .claude/ worth naming individually
_CLAUDE_SUB = {"skills": "claude-skills", "hooks": "claude-hooks", "commands": "claude-commands"}


def _gh(path: str) -> list | dict:
    req = urllib.request.Request(
        f"https://api.github.com/{path}",
        headers={"Accept": "application/vnd.github+json", "User-Agent": "animate-anything-probe",
                 **({"Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}"} if os.environ.get("GITHUB_TOKEN") else {})},
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())


def probe(slug: str) -> list[str]:
    """→ sorted surface tokens observed at the repo root (may be empty — that's a finding)."""
    names = {e["name"]: e["type"] for e in _gh(f"repos/{slug}/contents/")}
    surfaces = [tok for name, tok in _ROOT_SURFACES.items() if name in names]
    if ".claude" in names:
        try:
            sub = {e["name"] for e in _gh(f"repos/{slug}/contents/.claude")}
            surfaces += [tok for name, tok in _CLAUDE_SUB.items() if name in sub]
            if not any(s.startswith("claude-") for s in surfaces):
                surfaces.append("claude-dir")
        except urllib.error.HTTPError:
            surfaces.append("claude-dir")
    return sorted(surfaces)


def gh_slug(url: str) -> str:
    m = re.search(r"github\.com/([\w.-]+/[\w.-]+)", url)
    return m.group(1).rstrip("/").removesuffix(".git") if m else ""


def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog="agentic_probe.py")
    p.add_argument("--graph", default="knowledge/graph.json")
    p.add_argument("--out", default="knowledge/agentic.json")
    p.add_argument("--rank", type=int, default=1, help="probe repos ranked ≤ this (1 = 🥇 only)")
    args = p.parse_args(argv)

    g = json.load(open(args.graph))
    targets: dict[str, list[str]] = {}  # slug → node ids (Remotion rows share one repo)
    for n in g["nodes"]:
        if n.get("type") == "repo" and n.get("rank") and n["rank"] <= args.rank:
            slug = next((gh_slug(u) for u in n.get("links", []) if gh_slug(u)), "")
            if slug:
                targets.setdefault(slug, []).append(n["id"])

    overlay_nodes, errors = [], 0
    for slug, nids in sorted(targets.items()):
        try:
            surfaces = probe(slug)
        except Exception as e:  # not measured ≠ measured-empty: omit, warn, fail the run
            errors += 1
            print(f"  ⚠ {slug}: not measured ({e})", file=sys.stderr)
            continue
        print(f"  {slug:<40} {' '.join(surfaces) or '(none observed)'}")
        for nid in nids:
            overlay_nodes.append({"id": nid, "agentic": surfaces, "agentic_probe": f"github:{slug}"})

    out = {"comment": "GENERATED by scripts/agentic_probe.py — observed agentic surfaces of top repos; "
                      "a repo absent here was not measured, not surface-free.",
           "nodes": overlay_nodes}
    json.dump(out, open(args.out, "w"), indent=1, ensure_ascii=False)
    print(f"agentic: {args.out} — {len(overlay_nodes)} node annotations from {len(targets) - errors}/{len(targets)} repos")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
